recipes: add initial Bugzilla service
ferdium/ferdium-recipes pull request #153
Opened 2022-08-17 02:37 UTC by xgqt

Closes: https://github.com/ferdium/ferdium-recipes/issues/150
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

2022-08-23 16:54 UTC, xgqt commented
@vraravam ping
Could you check it one out? Thanks in advance. :D

2022-08-27 03:11 UTC, vraravam requested changes

2022-08-27 03:11 UTC, vraravam commented on recipes/bugzilla/package.json
> +    "serviceURL": "",
Please provide a default url for bugzilla

2022-08-27 13:55 UTC, vraravam approved these changes
The empty webview will mean that you don't get notifications/unread badges, etc. I hope that's fine. Approving with this caveat

2022-08-27 13:59 UTC, vraravam commented
@xgqt - please see the reason for the broken build. Please fix before this can be merged.

2022-08-27 14:01 UTC, xgqt commented
> @xgqt - please see the reason for the broken build. Please fix before this can be merged.

Sure, I will take care of reshaping the svg file.

2022-10-04 09:15 UTC, vraravam approved these changes
Accepting the base shell. Need to fix issues as they arise based on unread counter badges, etc

2022-10-04 09:16 UTC, merged

2022-10-04 09:16 UTC, vraravam commented
@all-contributors please add @xgqt for code