updated proton mail icon
ferdium/ferdium-recipes pull request #167
Opened 2022-08-30 02:50 UTC by haykh

see details about the [redesign](https://proton.me/blog/new-visual-universe).

2022-09-05 13:23 UTC, nathanaelhoun requested changes
Thanks for the referenced update!

Please bump the recipe version and run the validation checks  as stated in the [update guide](https://github.com/ferdium/ferdium-recipes/blob/main/docs/updating.md#4-updating-the-version-number)

2022-09-05 20:55 UTC, haykh commented
done!

2022-09-06 07:36 UTC, SpecialAro approved these changes

2022-09-07 08:41 UTC, merged

2022-09-07 08:42 UTC, nathanaelhoun commented
@all-contributors please add @haykh for code