Fix Hangouts badge counter
ferdium/ferdium-recipes pull request #324
Opened 2023-03-11 13:15 UTC by tamas646

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Fixed the counting of the notifications in the Hangouts recipe.

2023-03-11 14:26 UTC, vraravam requested changes

2023-03-11 14:26 UTC, vraravam commented on recipes/hangouts/webview.js
> +    for (const span of document.querySelectorAll('span[jsname=DW2nlb]'))  count += span.textContent == '' ? 0 : Number.parseInt(span.textContent);
Please use `Ferdium.safeParseInt` which will remove the need for the ternary null/blank check.

2023-03-11 14:26 UTC, vraravam commented on recipes/hangouts/package.json
> +  "version": "1.4.0",
please bump only the tiny segment (3rd segment) for this change

2023-03-11 16:38 UTC, tamas646 commented
I've made the requested changes.

2023-03-12 00:14 UTC, vraravam approved these changes

2023-03-12 00:15 UTC, vraravam commented
I dont use hangouts chat recipe, so I haven't tested this locally. but the changes look good.

2023-03-12 00:15 UTC, merged

2023-03-12 00:16 UTC, vraravam commented
@all-contributors please add @tamas646 for code