Change of Proton Service URL
ferdium/ferdium-recipes pull request #36
Opened 2022-05-26 16:38 UTC by Latschenharry

2022-05-26 17:02 UTC, vraravam requested changes
Need to update the respective `package.json` for `version` in both the recipes

2022-05-26 17:04 UTC, Latschenharry commented
version number change done

2022-05-26 18:21 UTC, vraravam approved these changes

2022-05-26 18:22 UTC, merged

2022-06-21 00:03 UTC, vraravam commented
@all-contributors please add @Latschenharry for code