TEST PR for recipe version bump check
ferdium/ferdium-recipes pull request #362
Opened 2023-05-11 17:27 UTC by nathanaelhoun

This is a test PR

2023-05-12 20:05 UTC, nathanaelhoun commented
Hi @Alphrag, if it seems go to you, you can merge it, I will be away for the week-end.

After the merge, rebasing #360 should resolve the failing CI.

2023-05-12 21:28 UTC, Alphrag requested changes

2023-05-12 21:28 UTC, Alphrag commented on .github/workflows/check-pr.yml
>            token: ${{ secrets.GITHUB_TOKEN }}
The action `tj-actions/changed-files` does not appear to need the token (there is no input parameter of that kind), so this can be removed.

2023-05-12 21:30 UTC, Alphrag commented
This is exactly the action I thought of when I realised the previous one was not working as expected, thanks @nathanaelhoun for checking was changes were required and testing it.

2023-05-14 22:20 UTC, Alphrag approved these changes

2023-05-14 22:21 UTC, merged