Add mirotalk-bro recipe
ferdium/ferdium-recipes pull request #379
Opened 2023-06-04 13:38 UTC by miroslavpejic85

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

New release - add MiroTalk Live Broadcast to recipes.

MiroTalk WebRTC Live broadcasting involves the real-time transmission of audio, video, and data streams from a broadcaster to multiple viewers. Instead of relying on a centralized server to distribute the stream to viewers, WebRTC enables a direct connection between the broadcaster and each viewer. This approach offers several advantages, such as lower latency, scalability, and reduced infrastructure costs.

Live demo: https://bro.mirotalk.com/
GitHub: https://github.com/miroslavpejic85/mirotalkbro
Note: Unlimited time, unlimited rooms each having a broadcast and many viewers.

Thank you!

2023-06-04 14:29 UTC, vraravam commented on recipes/mirotalk-bro/package.json
> +	"id": "mirotalk-bro",
please fix indentation - we prefer 2 spaces

2023-06-04 15:46 UTC, vraravam requested changes

2023-06-04 15:46 UTC, vraravam commented on recipes/mirotalk-bro/package.json
> +	"id": "mirotalk-bro",
these are still using 4 spaces - please convert to 2 spaces (this is also specified/configured in the `.editorconfig` file at the root of the repo.

2023-06-04 15:55 UTC, miroslavpejic85 commented
This is very strange as per default the [.editorconfig](https://github.com/miroslavpejic85/ferdium-recipes-mirotalk/blob/main/.editorconfig) is configured correctly.

And also on my repo from where I sent the PR [seems ok](https://github.com/miroslavpejic85/ferdium-recipes-mirotalk/blob/main/recipes/mirotalk-bro/package.json) to me.

I missing something? :)

Thank you.

2023-06-04 23:40 UTC, vraravam approved these changes

2023-06-04 23:40 UTC, merged

2023-06-04 23:40 UTC, vraravam commented
@all-contributors please add @miroslavpejic85 for code

2023-06-05 06:46 UTC, miroslavpejic85 commented
Yes, already there, thank you so much guys!