Ensure that links are opened according to the user's preference
ferdium/ferdium-recipes pull request #417
Opened 2023-09-04 11:48 UTC by RJVB

Please ensure you've completed all of the following.

- [x ] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x ] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Since a few months certain links on instagram.com have started to open in the external browser, regardless of the service preference to open links in Ferdium. This issue is fixed with an adaptation of the event filter in the custom website recipe, modified to ignore NULL and script links (`#`).

Also fixes an occasional `element == null` dereference in getMessages().

Fixes: https://github.com/ferdium/ferdium-app/issues/1304

2023-09-05 22:05 UTC, SpecialAro requested changes
Overall LGTM but haven't tested! 😄 

Can you just fix my comments in order to merge it? Thank you very much!!

2023-09-05 22:05 UTC, SpecialAro commented on recipes/instagram/webview.js
> +            console.log('Opening %s in this window', url);
Can we remove this console.log testing code?

2023-09-05 22:05 UTC, SpecialAro commented on recipes/instagram/webview.js
> +            console.log('Opening %s in a new window', url);
Can we remove this too?

2023-09-24 11:32 UTC, mcmxcdev commented
@RJVB please bump update version in instagram `package.json` from 2.5.0 to 2.5.1, otherwises these changes will not be applied to users.

@SpecialAro Do you use Instagram (I don't), and can you make sure the PR works as expected? Otherwise, we will need another team member to look over this.

2023-09-24 11:43 UTC, RJVB commented
> @RJVB please bump update version in instagram `package.json` from 2.5.0 to 2.5.1, otherwises these changes will not be applied to users.

Done.

2023-09-25 08:54 UTC, SpecialAro commented
> @SpecialAro Do you use Instagram (I don't), and can you make sure the PR works as expected? Otherwise, we will need another team member to look over this.

I use it yes, and I will try to test it today. Nevertheless @RJVB would you be able to fix the issue with the build failing?

2023-09-25 10:17 UTC, RJVB commented
>Nevertheless @RJVB would you be able to fix the issue with the build failing?

Sorry, I have no ideas about such things and don't see why my changes would cause a build to fail. Build of what, btw - this is just a bunch of recipes, no?

2023-09-25 12:12 UTC, mcmxcdev commented
@SpecialAro This build failure is weird, I attempted to bump the package.json version by another patch version but it still fails.
Locally, I don't get these failures, `pnpm package` works fine. Can you have a look?

2023-09-25 12:15 UTC, SpecialAro commented
I will try to have a look. It is most likely a lint issue

2023-10-02 03:54 UTC, vraravam requested changes
Please run the formatter before this can be merged.

2023-10-11 14:24 UTC, SpecialAro requested changes

2023-10-11 15:19 UTC, Arthur-Huan commented on recipes/instagram/package.json
> +  "version": "2.5.2",
mcmxdev commented 2 weeks ago: 

> @SpecialAro This build failure is weird, I attempted to bump the package.json version by another patch version but it still fails.
Locally, I don't get these failures, pnpm package works fine. Can you have a look?

2023-10-11 16:40 UTC, SpecialAro approved these changes

2023-10-11 16:40 UTC, merged