Update PushOver notification count
ferdium/ferdium-recipes pull request #431
Opened 2023-09-26 05:11 UTC by daudfatihah

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [ YES ] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [ YES ] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
change to count message using message_row class quantity instead app_counter(not exist)

2023-10-02 02:06 UTC, mcmxcdev commented
Hey @daudfatihah, thanks a lot for the PR!

Please go into the `package.json` of the pushover recipe and change the version from v1.1.0 to v1.1.1

Only then users will be able to receive the updated code from this PR, and we will be able to merge this.

2023-10-02 02:07 UTC, mcmxcdev commented on recipes/pushover/webview.js
> +    Ferdium.setBadge(totalMessages)
This line is missing a semicolon which will probably break the prettier formatting check:

```suggestion
    Ferdium.setBadge(totalMessages);
```

2023-10-02 03:18 UTC, daudfatihah commented
> Hey @daudfatihah, thanks a lot for the PR!
> 
> Please go into the `package.json` of the pushover recipe and change the version from v1.1.0 to v1.1.1
> 
> Only then users will be able to receive the updated code from this PR, and we will be able to merge this.

Done update to v1.1.1

2023-10-02 03:49 UTC, vraravam requested changes
please update this PR with the version bump in the `package.json` for this recipe

2023-10-02 05:28 UTC, vraravam approved these changes

2023-10-02 05:31 UTC, vraravam requested changes
@daudfatihah - the PR is failing ; probably because of lint issues. Please make sure to follow the contribution guide and run all the steps before this PR can be accepted and merged

2023-10-02 07:17 UTC, vraravam commented
@daudfatihah - CI build is broken. Please fix by going through the commands detailed in the contribution guide. Please do not request for review without fixing those.

2023-10-11 15:18 UTC, mcmxcdev approved these changes

2023-10-17 23:10 UTC, SpecialAro approved these changes
LGTM! Haven't tested because I don't use PushOver

2023-10-17 23:10 UTC, merged

2023-10-17 23:11 UTC, SpecialAro commented
@all-contributors please add daudfatihah for code