fix badge for Instagram
ferdium/ferdium-recipes pull request #468
Opened 2023-11-24 23:08 UTC by Mralexandresys

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
I have fixed the badge of notifications for the Instagram and Instagram-direct-messages applications. The query selector now directly retrieves the value within the <span> that contains the number of notifications.

2023-11-25 18:38 UTC, mcmxcdev commented
Thank you for this fix!

To be able to merge this, please update the version in package.json of the instagram recipe as described in https://github.com/ferdium/ferdium-recipes/blob/main/docs/updating.md#4-updating-the-version-number

2023-11-25 22:19 UTC, Mralexandresys commented
Thank you for feedback !

I update version and complet the fix

2023-11-25 23:10 UTC, vraravam approved these changes

2023-11-25 23:12 UTC, vraravam requested changes
Please fix the formatting error before this can be approved

2023-11-26 00:41 UTC, Mralexandresys commented
I running the commande `pnpm lint:fix && pnpm reformat-files && pnpm package` on my local and check pass

2023-11-26 01:34 UTC, merged