Add Iranian messengers
ferdium/ferdium-recipes pull request #551
Opened 2024-05-20 13:16 UTC by xmha97

Dear developer(s)
"‌Bale" and "Eitaa" messengers are widely used in Iran and I want you to add them to this app
Thank you for making this app

2024-05-20 13:50 UTC, vraravam requested changes

2024-05-20 13:50 UTC, vraravam commented on recipes/bale/package.json
> +  "version": "1.0.1",
pls change this to `1.0.0`

2024-05-20 13:50 UTC, vraravam commented on recipes/eitaa/package.json
> +  "version": "1.0.1",
pls change this to `1.0.0`

2024-05-23 21:51 UTC, xmha97 commented
@vraravam Hi, I fix the version.

2024-05-24 00:07 UTC, vraravam approved these changes

2024-05-24 00:13 UTC, vraravam commented
@xmha97 - please see the error shown by the CI run and fix it. Thanks for your contribution!

2024-05-25 22:55 UTC, xmha97 commented
> @xmha97 - please see the error shown by the CI run and fix it. Thanks for your contribution!

@vraravam - I think the error is fixed now.

2024-05-26 02:28 UTC, merged

2024-05-26 02:28 UTC, vraravam commented
Thanks for your contribution @xmha97 

@all-contributors please add @xmha97 for code