Add Rubika & Soroush
ferdium/ferdium-recipes pull request #559
Opened 2024-06-06 14:35 UTC by xmha97

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I updated the version package [Updating](https://github.com/ferdium/ferdium-recipes/blob/main/docs/updating.md#4-updating-the-version-number) 

#### Description of Change

2024-06-06 14:45 UTC, xmha97 commented
Hi @vraravam
"Rubika" and "Soroush+" messengers are widely used in Iran and I want you to add them to this app.
Please merge this PR.
Thanks.

2024-06-07 22:19 UTC, vraravam requested changes
please do not make changes to multiple recipes in the same PR - please create separate PRs (1 per recipe)

2024-06-07 22:19 UTC, vraravam commented on recipes/eitaa/package.json
> +  "repository": "https://github.com/xmha97/FerdiumRecipes",
please remove the `repository` key

2024-06-07 22:19 UTC, vraravam commented on recipes/bale/package.json
> +  "repository": "https://github.com/xmha97/FerdiumRecipes",
please remove the `repository` key

2024-06-07 22:19 UTC, vraravam commented on recipes/rubika/package.json
> +  "repository": "https://github.com/xmha97/FerdiumRecipes",
please remove the `repository` key

2024-06-07 22:19 UTC, vraravam commented on recipes/rubika/package.json
> +    "روبیکا"
`alias` needs to be in english - pls change.

2024-06-07 22:19 UTC, vraravam commented on recipes/soroush/package.json
> +    "سروش پلاس"
alias needs to be in english - please change

2024-06-07 22:19 UTC, vraravam commented on recipes/soroush/package.json
> +  "repository": "https://github.com/xmha97/FerdiumRecipes",
please remove the `repository` key

2024-06-08 06:03 UTC, closed without merging