Injecting `darkmode.css` for Messenger when appropriate
ferdium/ferdium-recipes pull request #581
Opened 2024-08-22 05:08 UTC by Arthur-Huan

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I updated the version package [Updating](https://github.com/ferdium/ferdium-recipes/blob/main/docs/updating.md#4-updating-the-version-number) 

#### Description of Change

This is mostly a proof of concept.

Currently, none of the services display their dark themes even with the system in dark mode, Ferdium in dark mode, and the universal dark mode feature turned on. It's long bothered me that some recipes have `darkmode.css` files but don't seem to be injected anywhere. So I tested out making some changes to `webview.js`, to inject the CSS if it's detected that the system is in dark mode. It seems to work. I am proposing that the previous snippet be added to all recipes if they have a `darkmode.css` file.

To me, it seems this would solve the dark mode issue (assuming we have a functional `darkmode.css` file). But I do wish to be cautious and see what more senior and knowledgeable contributors think before I proceed.

2024-08-22 05:10 UTC, Arthur-Huan commented
Added note:

The original `darkmode.css` for Messenger doesn't work at all. I stole one from Instagram. It also doesn't work that well, but at least you can see some changes to show that the CSS is being injected properly during dark mode, and not injected during light mode. As a proof of concept.

It seems like most of the `darkmode.css` files would need changes as I've struggled finding one that works perfectly. Perhaps they're outdated as they seem to have just been copied from Franz and not updated since. That would be what I look at next, to see if I can update and fix them.

2024-08-22 07:47 UTC, SpecialAro reviewed
Hello 👋 

Thank you for opening this PR!

Nevertheless, we should not be using the prefers dark mode but the internal config for the service in order to inject the dark mode.

2024-08-22 07:47 UTC, SpecialAro commented on recipes/messenger/webview.js
> +    window.matchMedia('(prefers-color-scheme: dark)').matches
We should not be using this but instead use the internal config of the service for handling dark mode (I'm on mobile right now but should be something like service.isDarkMode)

2024-10-04 06:29 UTC, vraravam requested changes
same comment as @SpecialAro

2025-06-09 03:21 UTC, Arthur-Huan commented
Apologies, I forgot about this PR. At the time, I checked `service.isDarkMode` and some other potential options I thought of, but none worked. Then I got caught up and forgot about it. If I figure out how dark mode is handled in the source code I will open another PR. Closing this here.

2025-06-09 03:21 UTC, closed without merging