add voetbal-nl; update pnpm and docker version
ferdium/ferdium-recipes pull request #582
Opened 2024-09-04 10:50 UTC by richardbeumer

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I updated the version package [Updating](https://github.com/ferdium/ferdium-recipes/blob/main/docs/updating.md#4-updating-the-version-number) 

#### Description of Change

1. Add voetbal-nl recipe
2. Update pnpm to 9.7.1
3. Change to more recent version of dev-container

2024-09-04 17:20 UTC, SpecialAro commented
Hello 👋 thank you for taking the time to contribute!

May I ask you to remove all node updates (pnpm and dockerfile) from this PR, as we have a method for updating both ferdium-app and ferdium-recipes together?

Thank you!

2024-09-05 02:29 UTC, vraravam requested changes
I agree with @SpecialAro  - please remove the node and pnpm upgrades from this PR

2024-09-05 05:41 UTC, richardbeumer commented
I'm sorry, I wasn't aware there was a method to keep the recipes in sync with the app. Node and docker updates are removed from this PR.

2024-09-05 06:40 UTC, vraravam requested changes
Please also remove the `package-lock.json` file.

2024-09-05 06:40 UTC, vraravam commented on .gitignore
> +.pnpm-store
can we remove this change as well?

2024-09-05 07:14 UTC, richardbeumer commented on .gitignore
> +.pnpm-store
removed!!

2024-09-05 07:24 UTC, vraravam requested changes
Please revert changes in the `.gitignore` file. If needed, please squash your commits into a single one to ensure that the final changes are limited to the `recipesvoetbal-nl` folder alone

2024-09-05 07:50 UTC, richardbeumer commented
squashed all commits to one for now.

2024-09-05 07:59 UTC, vraravam approved these changes

2024-09-05 08:00 UTC, merged

2024-09-05 08:00 UTC, vraravam commented
@all-contributors please add @richardbeumer for code