Added Sharezone and Bycs Messenger
ferdium/ferdium-recipes pull request #587
Opened 2024-09-25 15:45 UTC by BlackDemon1000

Added Sharezone (School Manager) and Bycs Messenger (a Messenger Tool we use in our school)

2024-10-04 05:49 UTC, vraravam approved these changes
Thanks for your contribution and welcome to your [Hacktoberfest](https://hacktoberfest.com/profile/) contributions 🎉🎉🎉!

2024-10-04 05:51 UTC, vraravam requested changes
Please remove the changes the `pnpm-lock.yaml` from this PR before it can be accepted.

2024-10-13 01:13 UTC, vraravam commented
@BlackDemon1000  - please delete the `pnpm-lock.yaml` changes in your PR. Also, rebase from the latest version of the `main` branch before this PR can be taken forward.

2024-10-13 08:21 UTC, BlackDemon1000 commented
I will take care of it in the next few days, but I'm just a bit busy at the moment

2025-03-08 15:14 UTC, SpecialAro approved these changes

2025-03-08 15:14 UTC, merged

2025-03-08 15:14 UTC, SpecialAro commented
@all-contributors please add BlackDemon1000 for code