Fix outlook issue by changing the service URL
ferdium/ferdium-recipes pull request #9
Opened 2022-05-02 00:17 UTC by SpecialAro

This solves https://github.com/ferdium/ferdium-recipes/issues/8.

We previously had two recipes for outlook (one normal, and another for 365) - does this change affect anything on that?

2022-05-02 13:50 UTC, vraravam requested changes
Please run `pnpm run package` - that will fail since the recipe version needs a bump in the corresponding `package.json`

2022-05-02 13:57 UTC, vraravam commented
Also, since we are anyways editing this service recipe, could you please add the "outlook" as an alias in `package.json`?

2022-05-02 13:59 UTC, vraravam commented
I had a chance to try this on my client's outlook (that uses okta for SSO) - but, this change did not have any impact. Once Ferdium is closed and reopened, I was taken back to the okta sign-in page.

2022-05-03 19:32 UTC, SpecialAro commented
> Please run `pnpm run package` - that will fail since the recipe version needs a bump in the corresponding `package.json`
![image](https://user-images.githubusercontent.com/37463445/166541564-5f4d5fdd-2af3-4233-aecf-d44ee22c8686.png)

This didn't fail... But it should, because I didn't upgrade the json version, yes.

> Also, since we are anyways editing this service recipe, could you please add the "outlook" as an alias in package.json?
Next commit will have it.

> I had a chance to try this on my client's outlook (that uses okta for SSO) - but, this change did not have any impact. Once Ferdium is closed and reopened, I was taken back to the okta sign-in page.
Should we close this PR, given the fact that the issue may be other?

2022-05-03 19:58 UTC, vraravam commented
>  Should we close this PR, given the fact that the issue may be other?

Yes, im not sure if this is a valid change - for the intended goal.
Also, the old url works similarly from my testing. So, I'm not sure about the need for this PR

2022-05-05 22:23 UTC, vraravam commented
Closing as per discussion with @SpecialAro

2022-05-05 22:23 UTC, closed without merging